version: "3.3"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb:/data
    networks:
      - service-api
    restart: always
    env_file:
      - ./.env
    ports:
      - 27017:27017

volumes:
  mongodb: {}

networks:
  service-api: {}